/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import adminSystemView.AdminView;
import database.DatabaseManagement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Aspire
 */
public class AddUser extends javax.swing.JFrame {

    /**
     * Creates new form AddAdmin
     */
    public AddUser() {
        initComponents();
    }
    
    DatabaseManagement database = new DatabaseManagement();
    String Gender;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        NewAdmin = new javax.swing.JPanel();
        UserName = new javax.swing.JTextField();
        UserEmailAddress = new javax.swing.JTextField();
        UserUsername = new javax.swing.JTextField();
        NameLabel = new javax.swing.JLabel();
        EmailAdressLabel = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        ConfirmPAsswordLabel = new javax.swing.JLabel();
        GenderLabel = new javax.swing.JLabel();
        AddressLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        UserAddress = new javax.swing.JTextPane();
        GenderMale = new javax.swing.JRadioButton();
        GenderFemale = new javax.swing.JRadioButton();
        Save = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        ResetButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        UserID = new javax.swing.JTextField();
        UserPassword = new javax.swing.JPasswordField();
        UserConfirmPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New Employee");
        setResizable(false);

        NewAdmin.setBackground(new java.awt.Color(86, 101, 115));
        NewAdmin.setForeground(new java.awt.Color(255, 255, 255));

        UserName.setBackground(new java.awt.Color(128, 139, 150));
        UserName.setForeground(new java.awt.Color(255, 255, 255));
        UserName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameActionPerformed(evt);
            }
        });

        UserEmailAddress.setBackground(new java.awt.Color(128, 139, 150));
        UserEmailAddress.setForeground(new java.awt.Color(255, 255, 255));
        UserEmailAddress.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        UserUsername.setBackground(new java.awt.Color(128, 139, 150));
        UserUsername.setForeground(new java.awt.Color(255, 255, 255));
        UserUsername.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        NameLabel.setForeground(new java.awt.Color(255, 255, 255));
        NameLabel.setText("Name:");

        EmailAdressLabel.setForeground(new java.awt.Color(255, 255, 255));
        EmailAdressLabel.setText("Email Adress:");

        UsernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        UsernameLabel.setText("Username:");

        PasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel.setText("Password:");

        ConfirmPAsswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmPAsswordLabel.setText("confirm password:");

        GenderLabel.setForeground(new java.awt.Color(255, 255, 255));
        GenderLabel.setText("Gender:");

        AddressLabel.setForeground(new java.awt.Color(255, 255, 255));
        AddressLabel.setText("Address:");

        UserAddress.setBackground(new java.awt.Color(128, 139, 150));
        UserAddress.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        UserAddress.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(UserAddress);

        GenderMale.setBackground(new java.awt.Color(86, 101, 115));
        buttonGroup1.add(GenderMale);
        GenderMale.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        GenderMale.setForeground(new java.awt.Color(255, 255, 255));
        GenderMale.setText("M");
        GenderMale.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        GenderFemale.setBackground(new java.awt.Color(86, 101, 115));
        buttonGroup1.add(GenderFemale);
        GenderFemale.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        GenderFemale.setForeground(new java.awt.Color(255, 255, 255));
        GenderFemale.setText("F");
        GenderFemale.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Save.setBackground(new java.awt.Color(204, 255, 204));
        Save.setForeground(new java.awt.Color(255, 255, 255));
        Save.setText("Save");
        Save.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("New Employee");

        ResetButton.setBackground(new java.awt.Color(86, 101, 115));
        ResetButton.setForeground(new java.awt.Color(255, 255, 255));
        ResetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/restart-icon-18-16.png"))); // NOI18N
        ResetButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID:");

        UserID.setBackground(new java.awt.Color(128, 139, 150));
        UserID.setForeground(new java.awt.Color(255, 255, 255));
        UserID.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        UserPassword.setBackground(new java.awt.Color(128, 139, 150));
        UserPassword.setForeground(new java.awt.Color(255, 255, 255));
        UserPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        UserConfirmPassword.setBackground(new java.awt.Color(128, 139, 150));
        UserConfirmPassword.setForeground(new java.awt.Color(255, 255, 255));
        UserConfirmPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout NewAdminLayout = new javax.swing.GroupLayout(NewAdmin);
        NewAdmin.setLayout(NewAdminLayout);
        NewAdminLayout.setHorizontalGroup(
            NewAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewAdminLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(NewAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewAdminLayout.createSequentialGroup()
                        .addGroup(NewAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UsernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(PasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(NameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(EmailAdressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NewAdminLayout.createSequentialGroup()
                        .addGroup(NewAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NewAdminLayout.createSequentialGroup()
                                .addGroup(NewAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GenderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewAdminLayout.createSequentialGroup()
                                .addComponent(ConfirmPAsswordLabel)
                                .addGap(18, 18, 18)))
                        .addGroup(NewAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NewAdminLayout.createSequentialGroup()
                                .addComponent(GenderMale)
                                .addGap(86, 86, 86)
                                .addComponent(GenderFemale))
                            .addGroup(NewAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(NewAdminLayout.createSequentialGroup()
                                    .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(NewAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(UserUsername)
                                .addComponent(UserEmailAddress)
                                .addComponent(UserName)
                                .addComponent(UserID)
                                .addComponent(UserPassword)
                                .addComponent(UserConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        NewAdminLayout.setVerticalGroup(
            NewAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(NewAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(UserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(NewAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameLabel))
                .addGap(18, 18, 18)
                .addGroup(NewAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailAdressLabel))
                .addGap(18, 18, 18)
                .addGroup(NewAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameLabel))
                .addGap(18, 18, 18)
                .addGroup(NewAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLabel)
                    .addComponent(UserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(NewAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmPAsswordLabel)
                    .addComponent(UserConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(NewAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenderLabel)
                    .addComponent(GenderMale)
                    .addComponent(GenderFemale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NewAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddressLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(NewAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ResetButton, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NewAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NewAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        String Userid = this.UserID.getText();
        String Username = this.UserName.getText();
    	String Userusername = this.UserUsername.getText();
        String Userpassword = this.UserPassword.getText();
    	String UseremailAddress = this.UserEmailAddress.getText();
    	String UserconfirmPassword = this.UserConfirmPassword.getText();
        String Useraddress = this.UserAddress.getText();        
        if(GenderMale.isSelected()){
            Gender = "Male";
        }
        if(GenderFemale.isSelected()){
            Gender = "Female";
        }
  
        
        ArrayList user = new ArrayList();
        
    	
    	Boolean empty =  Userid.isEmpty() || Username.isEmpty() || Userusername.isEmpty() || Userpassword.isEmpty() || UseremailAddress.isEmpty()|| UserconfirmPassword.isEmpty()|| Useraddress.isEmpty() || (!GenderFemale.isSelected() && !GenderMale.isSelected());
    	
    	if(empty) { 
            JOptionPane.showMessageDialog(rootPane,"Plase fill all the feilds"," Error !",JOptionPane . ERROR_MESSAGE);
                
    	}
        else if (!Userpassword.equals(UserconfirmPassword)){
            JOptionPane.showMessageDialog(rootPane,"Password not matched"," Error !",JOptionPane . ERROR_MESSAGE);
        }
        else{
            user.add(Userid);
            user.add(Username);
            user.add(UseremailAddress);
            user.add(Userusername);
            user.add(Userpassword);
            user.add(Gender);
            user.add(Useraddress);
  
            database.InsertIntoUser(user);

        } 
        AdminView v = new AdminView();
        v.showUser();
    }//GEN-LAST:event_SaveActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        UserID.setText("");
        UserName.setText("");
        UserUsername.setText("");
        UserPassword.setText("");
        UserEmailAddress.setText("");
        UserConfirmPassword.setText("");
        UserAddress.setText("");
        GenderFemale.setSelected(false);
        GenderMale.setSelected(false);
        
    }//GEN-LAST:event_ResetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JLabel ConfirmPAsswordLabel;
    private javax.swing.JLabel EmailAdressLabel;
    private javax.swing.JRadioButton GenderFemale;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JRadioButton GenderMale;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JPanel NewAdmin;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton Save;
    private javax.swing.JTextPane UserAddress;
    private javax.swing.JPasswordField UserConfirmPassword;
    private javax.swing.JTextField UserEmailAddress;
    private javax.swing.JTextField UserID;
    private javax.swing.JTextField UserName;
    private javax.swing.JPasswordField UserPassword;
    private javax.swing.JTextField UserUsername;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
