package login;

import adminSystemView.AdminView;
import database.DatabaseManagement;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import systemView.View;


public class Login extends javax.swing.JFrame {

    public Login() {
        initComponents();
    }
    
    DatabaseManagement database = new DatabaseManagement();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Username = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        Login = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        ForgetLabel = new javax.swing.JLabel();
        Message = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ParkCars");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(86, 101, 115));
        jPanel1.setPreferredSize(new java.awt.Dimension(801, 524));

        Username.setBackground(new java.awt.Color(128, 139, 150));
        Username.setForeground(new java.awt.Color(102, 102, 102));
        Username.setText("Username");
        Username.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UsernameFocusLost(evt);
            }
        });

        Password.setBackground(new java.awt.Color(128, 139, 150));
        Password.setForeground(new java.awt.Color(102, 102, 102));
        Password.setText("Password");
        Password.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordFocusLost(evt);
            }
        });
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordKeyPressed(evt);
            }
        });

        Login.setBackground(new java.awt.Color(86, 101, 115));
        Login.setForeground(new java.awt.Color(204, 255, 204));
        Login.setText("Login");
        Login.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        Cancel.setBackground(new java.awt.Color(86, 101, 115));
        Cancel.setForeground(new java.awt.Color(255, 102, 102));
        Cancel.setText("Cancel");
        Cancel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        ForgetLabel.setBackground(new java.awt.Color(34, 58, 84));
        ForgetLabel.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        ForgetLabel.setForeground(new java.awt.Color(204, 204, 255));
        ForgetLabel.setText("Forgotten Password  or username?");
        ForgetLabel.setToolTipText("Contact to Office");
        ForgetLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ForgetLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Message.setBackground(new java.awt.Color(136, 159, 159));
        Message.setForeground(new java.awt.Color(255, 0, 51));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/username.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/password.png"))); // NOI18N

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(86, 101, 115));
        jTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Username)
                    .addComponent(Password, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(61, 61, 61))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(ForgetLabel))
                    .addComponent(Message, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Username))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Password))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Login)
                            .addComponent(Cancel))
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addComponent(Message, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ForgetLabel)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
                
        String query = "select * from user;";
        ResultSet result = database.execQuery(query);
        
        String queryadmin = "select * from admin;";
        ResultSet resultadmin = database.execQuery(queryadmin);
        
      
        try{
            while(result.next()){

                String UserUsername = result.getString("UserUsername");
                String UserPassword = result.getString("UserPassword");
                String Uname = result.getString("UserName");
                String Uid = result.getString("UserID");
                String Uemail = result.getString("UserEmailAddress");
                String Uad = result.getString("UserAddress");
                
                if(Username.getText().equals(UserUsername) && Password.getText().equals(UserPassword)){
                Message.setText("Login Success");
                View view = new View(Uname,Uid,UserUsername,Uemail,Uad,UserPassword);
                view.setVisible(true);
                view.pack();
                this.dispose();
            }
            else {
                Message.setText("Write correct username or  password");
            }
    
        }
        }catch(SQLException e){
            System.out.println("Error: " + e);
            e.printStackTrace();
        }
 
        try{
            while(resultadmin.next()){

                String AdminUsername = resultadmin.getString("AdminUsername");
                String AdminPassword = resultadmin.getString("AdminPassword");
                String Aname = resultadmin.getString("AdminName");
                String Aemail = resultadmin.getString("AdminEmailAddress");
                String Aad = resultadmin.getString("AdminAddress");
                String Aid = resultadmin.getString("AdminID");
                
                if(Username.getText().equals(AdminUsername) && Password.getText().equals(AdminPassword)){
                Message.setText("Login Success");
                AdminView view = new AdminView(Aname,Aid,AdminUsername,Aemail,Aad,AdminPassword);
                view.setVisible(true);
                view.pack();
                this.dispose();
            }
            else {
                Message.setText("Write correct username or  password");
            }
    
        }
        }catch(SQLException e){
            System.out.println("Error: " + e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_LoginActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CancelActionPerformed

    private void UsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFocusLost
        if(Username.getText().trim().equals("")){
            Username.setText("Username");
            Username.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_UsernameFocusLost

    private void UsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFocusGained
        if(Username.getText().trim().equals("Username")){
            Username.setText("");
            Username.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_UsernameFocusGained

    private void PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusLost
        if(Password.getText().trim().equals("")){
            Password.setText("Password");
            Password.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_PasswordFocusLost

    private void PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusGained
        if(Password.getText().trim().equals("Password")){
            Password.setText("");
            Password.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_PasswordFocusGained

    private void PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
           String query = "select * from user;";
        ResultSet result = database.execQuery(query);
        
        String queryadmin = "select * from admin;";
        ResultSet resultadmin = database.execQuery(queryadmin);
        
        if(Username.getText().equals("ss") && Password.getText().equals("ss")){
        Message.setText("Login Success");
        AdminView view = new AdminView();
        view.setVisible(true);
        view.pack();
        this.dispose();
        }
      
        try{
            while(result.next()){

                String UserUsername = result.getString("UserUsername");
                String UserPassword = result.getString("UserPassword");
                String Uname = result.getString("UserName");
                String Uid = result.getString("UserID");
                String Uemail = result.getString("UserEmailAddress");
                String Uad = result.getString("UserAddress");
                
                if(Username.getText().equals(UserUsername) && Password.getText().equals(UserPassword)){
                Message.setText("Login Success");
                View view = new View(Uname,Uid,UserUsername,Uemail,Uad,UserPassword);
                view.setVisible(true);
                view.pack();
                this.dispose();
            }
            else {
                Message.setText("Write correct username or  password");
            }
    
        }
        }catch(SQLException e){
            System.out.println("Error: " + e);
            e.printStackTrace();
        }
 
        try{
            while(resultadmin.next()){

                String AdminUsername = resultadmin.getString("AdminUsername");
                String AdminPassword = resultadmin.getString("AdminPassword");
                String Aname = resultadmin.getString("AdminName");
                String Aemail = resultadmin.getString("AdminEmailAddress");
                String Aad = resultadmin.getString("AdminAddress");
                String Aid = resultadmin.getString("AdminID");
                
                if(Username.getText().equals(AdminUsername) && Password.getText().equals(AdminPassword)){
                Message.setText("Login Success");
                AdminView view = new AdminView(Aname,Aid,AdminUsername,Aemail,Aad,AdminPassword);
                view.setVisible(true);
                view.pack();
                this.dispose();
            }
            else {
                Message.setText("Write correct username or  password");
            }
    
        }
        }catch(SQLException e){
            System.out.println("Error: " + e);
            e.printStackTrace();
        }
       }
    }//GEN-LAST:event_PasswordKeyPressed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel ForgetLabel;
    private javax.swing.JButton Login;
    private javax.swing.JLabel Message;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
